// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulbjqdwnmjvmsrjrball.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsYmpxZHdubWp2bXNyanJiYWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjgwNzcsImV4cCI6MjA2MzM0NDA3N30.BKMJMIatvmGbXhRKX_BCNa8uDQZvFlPK9RpvHnaNpx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);